language: python
python:
  - "2.7"
cache: pip
addons:
  apt:
    packages:
      - libsnappy-dev
      - oracle-java8-set-default
install:
  - pip install tox-travis codecov
script:
  - tox
after_success:
  - codecov
